#这是一行注释

<<<<<<< HEAD

#hehehehehe
=======
#注释狂魔
>>>>>>> branch 'master' of https://github.com/1660558389/sp-config.git
spring:
  application:
    name: item-service
    
#server:
#  port: 8001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

---
spring:
  profiles: item1
  
server:
  port: 8001
---
spring:
  profiles: item2

server:
  port: 8002
